name: Android CI

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (required by Android Gradle plugin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: '30.0.3'

      # Grant execute permissions to gradlew
      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew
        working-directory: FeedingTheFurballs

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: FeedingTheFurballs

      # Lint Check
      - name: Run Lint Check
        run: ./gradlew lint
        working-directory: FeedingTheFurballs

      # Upload APK Artifact for Debugging/Testing
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: FeedingTheFurballs/app/build/outputs/apk/debug/*.apk
