name: Android CI

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: '30.0.3'

      # Navigate to the project directory
      - name: Navigate to project directory
        run: cd Application/FeedingTheFurballs

      # Build APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: Application/FeedingTheFurballs  # Ensure the correct path to gradlew

      # Lint Check
      - name: Run Lint Check
        run: ./gradlew lint
        working-directory: Application/FeedingTheFurballs

      # Upload APK Artifact for Debugging/Testing
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: Application/FeedingTheFurballs/app/build/outputs/apk/debug/*.apk
