# .github/workflows/build_apk.yml
name: Build APK

on:
  push:
    branches:
      - Dillon  # Only builds on the Dillon branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: Dillon  # Ensures checkout of the Dillon branch

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: '34.0.0'

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x FeedingTheFurballs/gradlew

      # Build the APK
      - name: Build APK
        working-directory: FeedingTheFurballs
        run: ./gradlew assembleRelease

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: FeedingTheFurballs/app/build/outputs/apk/release/app-release.apk
